### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by dobber** [ndaversa/hubot-victorops-bot#2]
Hello

I'm having trouble setting up the plugin and it might be because I'm not understanding the documentation correct:

Here are my questions:

HUBOT_VICTOROPS_POST_URL - This should be in the format:
https://alert.victorops.com/integrations/generic/VICTOROPS_ID/alert/API_ID/ <- trailing slash, no routing key?

HUBOT_VICTOROPS_TEAMS_MAP - I have only one team called "infrastructure-team". It's unclear how to format the json here. I tried HUBOT_VICTOROPS_TEAMS_MAP=\{\"ops\":\"infrastructure-team\"\} but did not get the expected result.

When asked for `whois oncall` the bot trows and error

```
[Tue Nov 08 2016 09:18:07 GMT+0200 (EET)] ERROR TypeError: robot.adapter.client.getChannelGroupOrDMByName is not a function
  at invalidChannel (/Users/dobber/Projects/Bishop/node_modules/hubot-victorops-bot/src/victorops.coffee:55:17, <js>:46:40)
  at TextListener.callback (/Users/dobber/Projects/Bishop/node_modules/hubot-victorops-bot/src/victorops.coffee:125:12, <js>:149:16)
  at executeListener (/Users/dobber/Projects/Bishop/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/Users/dobber/Projects/Bishop/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /Users/dobber/Projects/Bishop/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/Users/dobber/Projects/Bishop/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/Users/dobber/Projects/Bishop/node_modules/async/lib/async.js:268:15)
  at /Users/dobber/Projects/Bishop/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by dobber** [comment]
This PR clears the documentation issue a bit
https://github.com/ndaversa/hubot-victorops-bot/pull/3

The error at the end of my original comment is still unresolved. I had to comment out the code that throws the error and explored for a couple of hours until I understood how to configure this plugin.

Really frustrating

**Comment by ndaversa** [comment]
@dobber Are you using hubot-slack as an adapter? If so, which version?

**Comment by dobber** [comment]
```
"hubot-slack": "^4.2.1",
```

**Comment by ndaversa** [comment]
@dobber fixed by: https://github.com/ndaversa/hubot-victorops-bot/commit/3f1b29c4e71ffad8029c3620f8e7c750e267000f

Update to version `2.0.1` and let me know if you still have issues
